FROM node:20-alpine

WORKDIR /usr/src/app

COPY ./packages ./packages
COPY ./package.json ./package.json
COPY ./yarn.lock ./yarn.lock
COPY ./turbo.json ./turbo.json

COPY ./apps/user-app/ ./apps/user-app/

RUN yarn install
RUN yarn db:generate
RUN yarn turbo run build --filter=apps/user-app

EXPOSE 3000

CMD ["yarn", "run","start:user-app"]



