FROM node:22

WORKDIR /usr/src/app

COPY ./packages ./packages
COPY ./package.json ./package.json
COPY ./yarn.lock ./yarn.lock
COPY ./turbo.json ./turbo.json

COPY ./apps/bank-webhook/ ./apps/bank-webhook/

RUN yarn install
RUN yarn db:generate
RUN yarn run build
EXPOSE 3003

CMD sh -c "cd packages/db && npx prisma migrate deploy && \
+           npx prisma db seed && \
           cd ../.. && yarn run start:bank-webhook"