version: '3.8'

services:
  bank-webhook:
    build:
      context: ./my-turborepo
      dockerfile: ./docker/Dockerfile.backend
    environment: 
      - DATABASE_URL=postgresql://postgres:mysecretpassword@postgres:5432/postgres
    ports:
      - 3003:3003
    depends_on:
      - postgres
      
  user-app:
    build:
      context: ./my-turborepo
      dockerfile: ./docker/Dockerfile.frontend
    environment: 
      - DATABASE_URL=postgresql://postgres:mysecretpassword@postgres:5432/postgres
    ports:
      - 3000:3000
    depends_on:
      - postgres
  
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/data/db

volumes:
  dbdata:

