FROM node:22

ARG DATABASE_URL
WORKDIR /usr/src/app

COPY ./packages ./packages
COPY ./package.json ./package.json
COPY ./yarn.lock ./yarn.lock
COPY ./turbo.json ./turbo.json

COPY ./apps/user-app/ ./apps/user-app/

RUN yarn install
RUN yarn db:generate
RUN DATABASE_URL=${DATABASE_URL} yarn run build

EXPOSE 3000
CMD ["yarn", "run","start:user-app"]


